language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
install:
  - npm install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm start &
  - sleep 5
script:
  - npm test
  - npm run e2e
  - npm run lint
